### PR TITLE
Ensure user is an admin when logging in

### PR DESCRIPTION
**Pull request by jgoley**
This may not be totally secure. I suppose we should check the list of users on the admin Role since, in theory, a user could change the role property of their User object and gain access.

### CODE REVIEW

**Comment by jgoley** [comment]
Tried to rework this based on the above comment. If we restrict the Role Class to read/write of Admins only, then we won't be able to access the Admin role to check if a user is in the role while logging in. I suppose we can stick with checking the `role` property for now.

**Comment by jgoley** [comment]
@Broham Let's hold off merging this one. I think we should check the role for a user.

**Comment by Broham** [comment]
Ok sounds good @jgoley

**Comment by jgoley** [comment]
@Broham I think this is good to go now. I implemented checking the role for user on Parse login.

**Pull request merged**
