### PR TITLE
Show basic details on the survey index page

### PR DESCRIPTION
**Pull request by jgoley**
Add basic details to survey index page:
- User Count
- Form Count
- Question Count

PT Story: https://www.pivotaltracker.com/story/show/125343701

### CODE REVIEW

**Comment by Broham** [comment]
@jgoley - this looks great!  Lets make sure we add back in ways for users to activate/deactivate surveys and edit forms etc at some point

Also it looks like a previous merge caused a conflict with this branch.

**Comment by jgoley** [comment]
My bad about removing the activation/deactivation. I'll return it in this PR.

**Comment by jgoley** [comment]
@Broham I fixed the activate button...it was looking for invited users which was empty and causing errors.
I also styled buttons a little globally and applied the new styling to activate button.

**Comment by Broham** [comment]
@jgoley is it possible to deactivate a survey?  I don't see it on the survey details page any more - did we move it?

**Comment by jgoley** [comment]
@Broham Oh yeah, I forgot to mention that I was thinking we shouldn't allow this? Seems like it wouldn't be great if a survey suddenly disappeared from so many users' devices? Not sure though.

**Comment by Broham** [comment]
@jgoley oh interesting - so once a survey was active you are thinking it would never come down?  Lets throw this up on the mobile channel and see what others think

**Comment by Broham** [comment]
looks good :+1:

**Pull request merged**
