### PR TITLE
Multiple results

### PR DESCRIPTION
**Pull request by jgoley**
**Contains code from #103. It should be reviewed and merged first.**

Shows both multipleChoice and checkbox results.

PT Stories:
https://www.pivotaltracker.com/story/show/123151681
https://www.pivotaltracker.com/story/show/123151351

### CODE REVIEW

**Comment by Broham** [comment]
@jgoley - i'm not getting any results under the `form results` section, is this where I should be seeing the mluti-choice and checkbox result changes you made?  Also I noticed that if I click into participants and select a user, the following error gets logged to the console:
```instanceData.selected.find is not a function```

**Comment by jgoley** [comment]
@Broham Hmm, yeah, you should see results. I'll check it out. I think the console errors associated with participants are partially resolved in #108

**Comment by jgoley** [comment]
@Broham You may want to take a gander at the code again. I did some refactoring. specifically here: https://github.com/ecohealthalliance/mobile-survey/blob/52729cd395d827a022b3fe08c14ca290594da150/app/packages/results/imports/highcharts_helpers.coffee
and the two files that depend on the function exported from that file (number_results.coffee, scale_results.coffee)

I also commented out the CSV buttons...I'll fix those in a branch I've started.

**Comment by Broham** [comment]
@jgoley looks like I was missing some packages.  Seems to be working now - sorry for the confusion

**Pull request merged**
