### PR TITLE
Fix question editing

### PR DESCRIPTION
**Pull request by jgoley**
I think a recent change to the question details view structure caused several issues with handing down data and such.

PT Bug: https://www.pivotaltracker.com/story/show/121957395

@sturmer-eha @Broham **Question:** At some point we started a pattern where we add a property to the instance which references a property within the instance's data object. Is this a good idea.

While trouble shooting this bug I noticed another related to validating the edit form form: https://www.pivotaltracker.com/story/show/121973751

### CODE REVIEW

**Comment by Broham** [comment]
@jgoley looks like the last merge caused some conflicts in this PR

**Comment by Broham** [comment]
@jgoley it looks like you can no longer "edit" forms on this branch, which was how you added triggers.  I deactivated a survey, listed the forms and when i clicked the "edit" button nothing happened.  No error in console.

**Comment by jgoley** [comment]
I think that's been an issue since we introduced validation (https://www.pivotaltracker.com/story/show/121973751).  This PR should fix it: https://github.com/ecohealthalliance/mobile-survey/pull/83

**Comment by jgoley** [comment]
This should be good to go now. If you want I can merge #83 into this.

**Comment by Broham** [comment]
Thanks @jgoley looks great!

**Pull request merged**
