### PR TITLE
Geocode address

### PR DESCRIPTION
**Pull request by dan-nyanko**
- utilized typeahead and tokenfield to create a search bar
- created suggestionGenerator using openstreetmaps
- radius is now an input type=Number with step of .1
- map will zoom based on the current size of the radius
- map can be reset
- disabled keycode=13 on .edit-form
- custom fields are populated when editing vs create

### CODE REVIEW

**Comment by dan-nyanko** [comment]
also addresses 'floats' for radius in PT https://www.pivotaltracker.com/story/show/118152409

**Comment by Broham** [comment]
The address lookup seems a little funky.  The best way to look up addresses appears to be by entering them in the following format: `<street address> <zip code>`

I don't think that a lot of people will know this right off the bat.  We should look at updating the UI to force users to enter this information rather than entering addresses as they would for Google maps

Also the results can be a little strange.  My address: `10342 Gold Drive, Grass Valley, CA 95945` is being mapped to the address `10342, Gold Drive, The Oaks, Nevada County, California, 95945, USA`.  In addition to the format of the address being a little weird, there is no city called `The Oaks` in my county.

I think that this is a good starting point, but we should look at either making the Open Street Map solution a little more user friendly or possibly biting the bullet and paying for Google Maps.

**Comment by sturmer-eha** [comment]
The code looks pretty good. I would say if we've decided to switch to google maps API, then it might be a good idea to merge this one in and deal with google maps in a separate branch.

**Comment by Broham** [comment]
Yeah I agree @sturmer-eha 

@dan-nyanko if you can resolve the conflicts on this branch I will go ahead and merge.  We can look at switching to Google Maps API later.

**Pull request closed without merging**
