### PR TITLE
Disable edit/delete buttons associated with survey if active

### PR DESCRIPTION
**Pull request by jgoley**
- Disables edit/add/delete buttons in a survey that is active.
- Hides the question editing interface. We will need to add more details to the question detail view when a survey is active.
- Also moves question types array into imports folder and imports into add/edit views 

PT Chore: https://www.pivotaltracker.com/story/show/120767929

### CODE REVIEW

**Comment by Broham** [comment]
@jgoley - this looks pretty good but I had a few thoughts:

- Should we show a notification when a user clicks on edit/delete when they are disabled that informs them that they can't perform that action while the survey is active?  Seems like nothing happening might confuse some users otherwise.
- On the forms list page I noticed that when you mouse over the de-activated edit/delete buttons it shows the cursor with the x over it for a split second, but then reverts back to the pointer.  Seems like something is overriding the correct style?
- Should we let users click into questions in forms when they are disabled.  Currently when they do it just shows the question title and nothing else.
- It looks like users can change the question order even when the survey is active.  This is probably fine, but I wanted to make sure it is expected behavior.  Same thing with form order.
- Adding users is also disabled when the survey is active.  This seems like it might be something we would like admins to edit, even when it's active.  Thoughts?

**Comment by jgoley** [comment]
Great points. 
- I think maybe we can show a tooltip letting the user know the actions are disabled on an active survey.
- I was thinking we could show the responses of a question. I think Yuri and I talked about recycling templates so I just added the title for now. Might be better to build out in another branch?
- Seems like changing the question order in an activated survey would be okay. I honestly didn't think about it.
- I suppose we could allow user to be added post-activation. But this means some users may not see past-triggered questions.

I'll reopen the story/chore on PT and work on these changes.

**Comment by Broham** [comment]
@jgoley did your last commit take care of the stuff we talked about or is there more to do on this guy?

**Comment by jgoley** [comment]
@Broham I don't think so. I think its a new commit because I rebased against master and force pushed.

**Comment by jgoley** [comment]
I'm about to work on this. I'll let you know when its updated.

**Comment by jgoley** [comment]
@Broham I've updated this. I decided to hide the buttons from the user if a survey is active. I think we can make the sate of the survey with visual clues elsewhere. There was just too much no-op visual clutter.

I also have made questions plain text if the survey is active (rather than linked to more details). I'm planning to build out templates which show more info based on the type of question but I think it is too much and too different to include in this PR.

I think we can leave the sorting functionality while a survey is active for now.
I also choose to allow admins to add users post survey activation. Seems like this would be desirable.

**Comment by Broham** [comment]
Looks good :+1:

**Pull request merged**
