### PR TITLE
defined geofence trigger

### PR DESCRIPTION
**Pull request by dan-nyanko**
- user may click on the map and specify radius
- result is stored in mongo as geoJSON point

### CODE REVIEW

**Comment by sturmer-eha** [comment]
I think it might be a good idea to preventDefault for keyCode 13 (enter) for those fields above the map (they don't seem to belong to the form but rather to the map view)

min. value of range should not be 0 but probably 0.1 or something like that; never negative, also (unless we could use -1 in order to mark that location as being underground, but it's probably not that much of a good idea); should allow floats

the input fields above the map don't have to be so long, I think it'll be fine if we make them 40% of their current length, and maybe `background: rgba(200, 200, 200, .9)`?

the code looks good, I believe it's a good idea to merge now and then fix/improve later as needed, since the app is not live

**Comment by Broham** [comment]
@sturmer-eha - good points, i'm going to create a PT story for the range value validation things you mentioned.  The rest we can tackle as we see fit.

@dan-nyanko - if you can resolve the conflicts I will merge this in.

**Comment by Broham** [comment]
Related:
https://www.pivotaltracker.com/story/show/118152409

**Comment by dan-nyanko** [comment]
@sturmer-eha , @Broham -- please see PR https://github.com/ecohealthalliance/mobile-survey/pull/19 which is the next iteration of the two related stories

https://www.pivotaltracker.com/story/show/117435719
https://www.pivotaltracker.com/story/show/117440735

**Pull request merged**
