### PR TITLE
Install Validator package and validate forms

### PR DESCRIPTION
**Pull request by jgoley**
Uses bootstrap validator to validate survey, form and question forms.

Should I also add validation methods like we are doing here: https://github.com/ecohealthalliance/mobile-survey/blob/22ab61c593b047167f28e74adc9c1c2f07605f7d/app/imports/models.coffee#L4-L7

### CODE REVIEW

**Comment by dan-nyanko** [comment]
@jgoley seems like I can add a question without specifying a type, then when I edit the question it also does not have a type selected.  Upon inspecting the parse-dashboard I see it has been given the type of `inputText`.  This seems confusing.  If the user doesn't select a type, lets show an error.

**Comment by jgoley** [comment]
@dan-nyanko I'm having trouble adding questions without specifying a type. I receive a toastr notification. 
I do see the issue while editing a question—will fix.

**Comment by jgoley** [comment]
I think this may be because we have old data in the database—questions without `type` but with `questionType` properties.

**Comment by jgoley** [comment]
@dan-nyanko I've improved validation—now one a type is not chosen, an error is added inline instead of a toast. 
There is still one bug which I will have to come back to because I'm stumped. For some reason the bootstrap validator is not initialized on the edit question page even though the code is identical and I'm destroying the validation when each template is destroyed.

**Comment by Broham** [comment]
:+1: this look good going to merge

**Pull request merged**
