### PR TITLE
Implement survey details editing in list and on details page

### PR DESCRIPTION
**Pull request by jgoley**
I recycled the 'create_survey_modal' template which may overcomplicate things.
Will probably need to be refactored down the road.

PT Story: https://www.pivotaltracker.com/story/show/119380337

### CODE REVIEW

**Comment by Broham** [comment]
@jgoley - when editing the survey from the details page, nothing updates until you refresh the page.

**Comment by jgoley** [comment]
@Broham I missed this yesterday, sorry about that. Good catch. I'll fix that this morning.

**Comment by jgoley** [comment]
@Broham I've cleaned this up a bit. I decided the logic for implementing survey editing on the list view was getting too complex so I removed it for now.
I also implemented updating the survey details on save and the editing.

**Comment by Broham** [comment]
:+1: looks good - thanks @jgoley!

**Pull request merged**
