### PR TITLE
Do not allow user to delete active surveys

### PR DESCRIPTION
**Pull request by jgoley**
PT Story: https://www.pivotaltracker.com/story/show/119380281

### CODE REVIEW

**Comment by Broham** [comment]
This looks good @jgoley - if you can resolve the conflicts I will merge it.  Thanks!

**Comment by jgoley** [comment]
@Broham Good to go.

**Comment by jgoley** [comment]
@Broham Actually I found a bug. Will fix. Stay tuned.

**Comment by jgoley** [comment]
Okay..should be good to go now. Sorry about that.

**Comment by Broham** [comment]
:+1: Looks good merging

**Pull request merged**
