### PR TITLE
Base tests

### PR DESCRIPTION
**Pull request by jgoley**
This builds on the basic tests.

Looking to get some help from maybe @sturmer-eha. For some reason all the objects I'm trying to import [here](https://github.com/ecohealthalliance/mobile-survey/blob/1c07206048728befbee3aac6172385c1ba0ec0d9/app/packages/_tests/fixtures.coffee#L1)   are undefined. I've exposed all the files to the server and explicitly added `api.mainModule('index.coffee', 'server');` but no luck.

We'll need to solve this so we can use the api methods in fixtures.

### CODE REVIEW

**Comment by Broham** [comment]
@jgoley  ok - so it sounds like I should hold off on merging this?

**Comment by jgoley** [comment]
Yeah. The tests now depend on fixtures that return `undefined` because for some reason they can't access stuff from the API package. I'll circle back to this today at some point and try to fix it.

**Comment by jgoley** [comment]
@Broham I figured out the problem—there was a dependency not being fulfilled on the server. Some methods from the helpers package need to be available on the server.

The tests are passing now but there seems to be a problem with creating a form. I'll investigate this further on Monday.

**Comment by Broham** [comment]
@jgoley sounds good - let me know when the form issue gets resolved.

**Comment by jgoley** [comment]
So over the weekend I thought a little bit more about this. We probably shouldn't modify the application to run tests...if we don't need stuff on the server for production, we shouldn't during tests. So I've moved away from using meteor methods for the fixture data in favor of client-side methods passed through a module. But, of course, there are problems with this. For some reason the api package is not imported properly when tests are run so the fixtures don't have access to a bunch of necessary methods...even to Parse and Meteor. I'm not sure if its because we aren't using the post Meteor 1.3 imports structure or a mistake on my end.

**Comment by Broham** [comment]
@jgoley yeah I agree that we shouldn't modify the app for the tests.  I think this will be a better solution in the end.

**Comment by Broham** [comment]
@jgoley - is this guy ready to be merged?

**Comment by jgoley** [comment]
@Broham Not yet. I'm not sure how to proceed with this. May require @sturmer-eha's eye but I suspect he will propose not worrying about this right now.

**Comment by Broham** [comment]
@jgoley any objection to me closing this PR?  Since the plan is to wind down dev on GQ, i'm not sure it make sense to put more effort into this.  We should keep the branch around in case we decide we want to pick it up later

**Comment by jgoley** [comment]
@broham Nope. I think if we continue work on this app, we will need to reaccess a few things, including testing.

**Pull request closed without merging**
